"""TDD tests for textbook retrieval (specification/textbook-retrieval.md).

Tests are written BEFORE implementation. They will fail with ImportError
until the production modules exist under src/Poule/education/.

Covers: HTMLChunker (chunk_file, chunk_corpus, size control),
EducationEncoder (load, encode, encode_batch, model_hash),
EducationStorage (create, write/load chunks, write/load embeddings, meta),
EducationRAG (search, volume filtering, availability),
MCP tool handler (handle_education_context).
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from unittest.mock import Mock, patch, MagicMock

import numpy as np
import pytest


# ---------------------------------------------------------------------------
# Imports from production code (TDD — will fail until implemented)
# ---------------------------------------------------------------------------

from Poule.education.models import Chunk, ChunkMetadata, EducationSearchResult
from Poule.education.chunker import HTMLChunker
from Poule.education.encoder import EducationEncoder
from Poule.education.storage import EducationStorage
from Poule.education import EducationRAG


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _random_unit_vector(dim=384, seed=42):
    """Return a random L2-normalized vector of given dimension."""
    rng = np.random.RandomState(seed)
    v = rng.randn(dim).astype(np.float32)
    return v / np.linalg.norm(v)


def _random_embedding_matrix(n, dim=384, seed=42):
    """Return an (n, dim) matrix of L2-normalized row vectors."""
    rng = np.random.RandomState(seed)
    m = rng.randn(n, dim).astype(np.float32)
    norms = np.linalg.norm(m, axis=1, keepdims=True)
    return m / norms


def _vector_to_blob(v):
    """Serialize a float32 numpy vector to raw bytes."""
    return v.astype(np.float32).tobytes()


MINIMAL_HTML = """\
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Basics: Functional Programming in Rocq</title></head>
<body>
<div id="page">
<div id="header">
  <div class='booktitleinheader'><a href='index.html'>Volume 1: Logical Foundations</a></div>
  <ul id='menu'><li>nav</li></ul>
</div>
<div id="main">
<h1 class="libtitle">Basics<span class="subtitle">Functional Programming in Rocq</span></h1>

<div class="doc">
<a id="lab10"></a><h1 class="section">Introduction</h1>
<div class="paragraph"> </div>
This chapter introduces the basic concepts of functional programming in Rocq.
We start with enumerated types and work our way up.
</div>
<div class="code">
<span class="id" title="keyword">Inductive</span> <span class="id" title="definition">day</span> : <span class="id" title="keyword">Type</span> :=
  | <span class="id" title="constructor">monday</span>
  | <span class="id" title="constructor">tuesday</span>.
</div>

<div class="doc">
<a id="lab11"></a><h2 class="section">Days of the Week</h2>
<div class="paragraph"> </div>
Let us define an enumerated type for the days of the week.
This is a simple example of an inductive definition.
</div>

<div class="doc">
<a id="lab12"></a><h2 class="section">Booleans</h2>
<div class="paragraph"> </div>
Rocq provides a built-in boolean type. Let us explore how it works
and define some basic operations.
</div>
<div class="code">
<span class="id" title="keyword">Definition</span> <span class="id" title="definition">negb</span> (b : bool) : bool :=
  <span class="id" title="keyword">match</span> b <span class="id" title="keyword">with</span>
  | true =&gt; false
  | false =&gt; true
  <span class="id" title="keyword">end</span>.
</div>

<div class="doc">
<a id="lab13"></a><h4 class="section">Exercise: 1 star, standard (nandb)</h4>
<div class="paragraph"> </div>
Define nandb.
</div>

</div>
<div id="footer"><hr/>Generated by coqdoc</div>
</div>
</body>
</html>
"""

TINY_HTML = """\
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Tiny: A tiny chapter</title></head>
<body>
<div id="page">
<div id="header">
  <div class='booktitleinheader'><a href='index.html'>Volume 3: Verified Functional Algorithms</a></div>
</div>
<div id="main">
<h1 class="libtitle">Tiny<span class="subtitle">A tiny chapter</span></h1>

<div class="doc">
<a id="lab20"></a><h1 class="section">Only Section</h1>
<div class="paragraph"> </div>
Short.
</div>

</div>
<div id="footer"><hr/>Generated by coqdoc</div>
</div>
</body>
</html>
"""


def _write_html(tmp_path, volume, filename, content):
    """Write an HTML file into a volume directory."""
    vol_dir = tmp_path / volume
    vol_dir.mkdir(parents=True, exist_ok=True)
    path = vol_dir / filename
    path.write_text(content)
    return path


# ═══════════════════════════════════════════════════════════════════════════
# 1. HTMLChunker — chunk_file
# ═══════════════════════════════════════════════════════════════════════════


class TestHTMLChunkerChunkFile:
    """HTMLChunker.chunk_file parses HTML and produces section-based chunks."""

    def test_basic_chunking_produces_chunks(self, tmp_path):
        path = _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_file(path, "lf")
        assert len(chunks) > 0
        assert all(isinstance(c, Chunk) for c in chunks)

    def test_metadata_volume_and_chapter(self, tmp_path):
        path = _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_file(path, "lf")
        for c in chunks:
            assert c.metadata.volume == "lf"
            assert c.metadata.chapter_file == "Basics.html"
            assert c.metadata.volume_title == "Logical Foundations"
            assert "Basics" in c.metadata.chapter

    def test_section_titles_extracted(self, tmp_path):
        path = _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_file(path, "lf")
        section_titles = [c.metadata.section_title for c in chunks]
        assert "Introduction" in section_titles

    def test_anchor_ids_extracted(self, tmp_path):
        path = _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_file(path, "lf")
        anchor_ids = [c.metadata.anchor_id for c in chunks if c.metadata.anchor_id]
        assert len(anchor_ids) > 0
        assert "lab10" in anchor_ids

    def test_code_blocks_extracted(self, tmp_path):
        path = _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_file(path, "lf")
        all_code = []
        for c in chunks:
            all_code.extend(c.code_blocks)
        assert any("Inductive" in cb for cb in all_code)

    def test_header_and_footer_stripped(self, tmp_path):
        path = _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_file(path, "lf")
        all_text = " ".join(c.text for c in chunks)
        assert "Generated by coqdoc" not in all_text
        assert "nav" not in all_text.lower() or "navigation" not in all_text.lower()

    def test_token_count_populated(self, tmp_path):
        path = _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_file(path, "lf")
        for c in chunks:
            assert c.token_count > 0
            assert isinstance(c.token_count, int)

    def test_section_path_is_list(self, tmp_path):
        path = _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_file(path, "lf")
        for c in chunks:
            assert isinstance(c.metadata.section_path, list)


class TestHTMLChunkerSizeControl:
    """Chunk size control: merging small chunks, keeping exercises separate."""

    def test_tiny_section_merged(self, tmp_path):
        """A section under 100 tokens should be merged with the next."""
        path = _write_html(tmp_path, "vfa", "Tiny.html", TINY_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_file(path, "vfa")
        # The tiny chapter has one very short section — it should still produce
        # at least one chunk (possibly merged with introductory content).
        assert len(chunks) >= 1

    def test_exercise_kept_separate(self, tmp_path):
        path = _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_file(path, "lf")
        exercise_chunks = [c for c in chunks if "Exercise" in c.metadata.section_title]
        # The exercise in the test HTML should remain a separate chunk
        assert len(exercise_chunks) >= 1


class TestHTMLChunkerChunkCorpus:
    """HTMLChunker.chunk_corpus processes all volumes."""

    def test_chunk_corpus_multiple_volumes(self, tmp_path):
        _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        _write_html(tmp_path, "vfa", "Tiny.html", TINY_HTML)
        chunker = HTMLChunker()
        chunks = chunker.chunk_corpus(tmp_path)
        volumes = {c.metadata.volume for c in chunks}
        assert "lf" in volumes
        assert "vfa" in volumes

    def test_skips_non_content_pages(self, tmp_path):
        _write_html(tmp_path, "lf", "Basics.html", MINIMAL_HTML)
        _write_html(tmp_path, "lf", "index.html", "<html><body>index</body></html>")
        _write_html(tmp_path, "lf", "toc.html", "<html><body>toc</body></html>")
        _write_html(tmp_path, "lf", "coqindex.html", "<html><body>coqindex</body></html>")
        _write_html(tmp_path, "lf", "deps.html", "<html><body>deps</body></html>")
        chunker = HTMLChunker()
        chunks = chunker.chunk_corpus(tmp_path)
        files = {c.metadata.chapter_file for c in chunks}
        assert "index.html" not in files
        assert "toc.html" not in files
        assert "coqindex.html" not in files
        assert "deps.html" not in files


# ═══════════════════════════════════════════════════════════════════════════
# 2. EducationEncoder
# ═══════════════════════════════════════════════════════════════════════════


class TestEducationEncoderLoad:
    """EducationEncoder.load loads an ONNX model and tokenizer."""

    def test_load_nonexistent_model_raises(self, tmp_path):
        from Poule.neural.errors import ModelNotFoundError
        with pytest.raises(ModelNotFoundError):
            EducationEncoder.load(
                tmp_path / "nonexistent.onnx",
                tmp_path / "tokenizer.json",
            )

    def test_load_nonexistent_tokenizer_raises(self, tmp_path):
        model_path = tmp_path / "model.onnx"
        model_path.write_bytes(b"fake")
        with pytest.raises((FileNotFoundError, Exception)):
            EducationEncoder.load(model_path, tmp_path / "nonexistent.json")


class TestEducationEncoderEncode:
    """EducationEncoder.encode maps text to L2-normalized 384-dim vectors."""

    @pytest.fixture
    def mock_encoder(self):
        """Create a mock encoder that returns predictable vectors."""
        enc = Mock(spec=EducationEncoder)
        enc.encode.side_effect = lambda text: _random_unit_vector(
            384, seed=hash(text) % 2**31
        )
        enc.encode_batch.side_effect = lambda texts: [
            _random_unit_vector(384, seed=hash(t) % 2**31) for t in texts
        ]
        enc.model_hash.return_value = "abc123"
        return enc

    def test_encode_returns_384_dim(self, mock_encoder):
        vec = mock_encoder.encode("induction on natural numbers")
        assert vec.shape == (384,)

    def test_encode_l2_normalized(self, mock_encoder):
        vec = mock_encoder.encode("induction on natural numbers")
        norm = np.linalg.norm(vec)
        assert abs(norm - 1.0) < 1e-5

    def test_encode_deterministic(self, mock_encoder):
        v1 = mock_encoder.encode("same text")
        v2 = mock_encoder.encode("same text")
        np.testing.assert_array_equal(v1, v2)

    def test_encode_batch_preserves_order(self, mock_encoder):
        texts = ["alpha", "beta", "gamma"]
        batch = mock_encoder.encode_batch(texts)
        individual = [mock_encoder.encode(t) for t in texts]
        assert len(batch) == 3
        for b, i in zip(batch, individual):
            np.testing.assert_array_equal(b, i)


# ═══════════════════════════════════════════════════════════════════════════
# 3. EducationStorage
# ═══════════════════════════════════════════════════════════════════════════


def _make_chunk(
    text="Sample text",
    volume="lf",
    chapter="Basics",
    section="Introduction",
    anchor_id="lab10",
):
    return Chunk(
        text=text,
        code_blocks=["Definition x := 1."],
        metadata=ChunkMetadata(
            volume=volume,
            volume_title="Logical Foundations",
            chapter=chapter,
            chapter_file="Basics.html",
            section_title=section,
            section_path=["Introduction"],
            anchor_id=anchor_id,
        ),
        token_count=len(text.split()),
    )


class TestEducationStorageCreate:
    """EducationStorage.create creates a new database with the schema."""

    def test_create_new_db(self, tmp_path):
        db_path = tmp_path / "education.db"
        EducationStorage.create(db_path)
        assert db_path.exists()
        conn = sqlite3.connect(str(db_path))
        tables = [
            r[0]
            for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            ).fetchall()
        ]
        assert "chunks" in tables
        assert "education_embeddings" in tables
        assert "education_meta" in tables
        conn.close()

    def test_create_overwrites_existing(self, tmp_path):
        db_path = tmp_path / "education.db"
        db_path.write_text("old data")
        EducationStorage.create(db_path)
        conn = sqlite3.connect(str(db_path))
        tables = [
            r[0]
            for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            ).fetchall()
        ]
        assert "chunks" in tables
        conn.close()


class TestEducationStorageChunks:
    """EducationStorage write/load chunk round-trip."""

    def test_write_and_load_chunks(self, tmp_path):
        db_path = tmp_path / "education.db"
        EducationStorage.create(db_path)
        chunks = [
            _make_chunk("First section text", section="Intro"),
            _make_chunk("Second section text", section="Types"),
        ]
        ids = EducationStorage.write_chunks(db_path, chunks)
        assert len(ids) == 2
        loaded = EducationStorage.load_chunks(db_path)
        assert len(loaded) == 2
        for chunk_id in ids:
            assert chunk_id in loaded

    def test_loaded_chunk_has_correct_fields(self, tmp_path):
        db_path = tmp_path / "education.db"
        EducationStorage.create(db_path)
        chunk = _make_chunk(
            "Test text about induction",
            volume="lf",
            chapter="Basics",
            section="Induction",
            anchor_id="lab15",
        )
        ids = EducationStorage.write_chunks(db_path, [chunk])
        loaded = EducationStorage.load_chunks(db_path)
        c = loaded[ids[0]]
        assert c.text == "Test text about induction"
        assert c.metadata.volume == "lf"
        assert c.metadata.chapter == "Basics"
        assert c.metadata.section_title == "Induction"
        assert c.metadata.anchor_id == "lab15"
        assert c.metadata.chapter_file == "Basics.html"
        assert len(c.code_blocks) == 1


class TestEducationStorageEmbeddings:
    """EducationStorage write/load embedding round-trip."""

    def test_write_and_load_embeddings(self, tmp_path):
        db_path = tmp_path / "education.db"
        EducationStorage.create(db_path)
        chunks = [_make_chunk("text one"), _make_chunk("text two")]
        ids = EducationStorage.write_chunks(db_path, chunks)
        vectors = [_random_unit_vector(384, seed=i) for i in range(2)]
        EducationStorage.write_embeddings(db_path, ids, vectors)
        matrix, id_map = EducationStorage.load_embeddings(db_path)
        assert matrix.shape == (2, 384)
        assert id_map.shape == (2,)
        assert set(id_map.tolist()) == set(ids)
        # Verify vectors are L2-normalized after round-trip
        for row in range(matrix.shape[0]):
            norm = np.linalg.norm(matrix[row])
            assert abs(norm - 1.0) < 1e-4


class TestEducationStorageMeta:
    """EducationStorage metadata read/write."""

    def test_write_and_read_meta(self, tmp_path):
        db_path = tmp_path / "education.db"
        EducationStorage.create(db_path)
        EducationStorage.write_meta(db_path, {
            "schema_version": "1",
            "model_hash": "abc123",
            "chunk_count": "42",
        })
        conn = sqlite3.connect(str(db_path))
        rows = dict(conn.execute("SELECT key, value FROM education_meta").fetchall())
        conn.close()
        assert rows["schema_version"] == "1"
        assert rows["model_hash"] == "abc123"
        assert rows["chunk_count"] == "42"


# ═══════════════════════════════════════════════════════════════════════════
# 4. EducationRAG
# ═══════════════════════════════════════════════════════════════════════════


class TestEducationRAGSearch:
    """EducationRAG.search returns ranked results."""

    @pytest.fixture
    def rag_with_data(self, tmp_path):
        """Build a small education DB and create a RAG instance with mocked encoder."""
        db_path = tmp_path / "education.db"
        EducationStorage.create(db_path)
        chunks = [
            _make_chunk("Induction is the key proof technique for natural numbers", section="Induction"),
            _make_chunk("Rewriting replaces one side of an equation with the other", section="Rewriting"),
            _make_chunk("Case analysis splits a proof into branches", section="Case Analysis"),
        ]
        ids = EducationStorage.write_chunks(db_path, chunks)
        # Create embeddings where chunk 0 is similar to query about induction
        vectors = _random_embedding_matrix(3, 384, seed=99)
        EducationStorage.write_embeddings(db_path, ids, list(vectors))

        # Mock encoder that returns vectors close to chunk 0
        mock_encoder = Mock(spec=EducationEncoder)
        mock_encoder.encode.return_value = vectors[0]  # query matches chunk 0
        mock_encoder.model_hash.return_value = "test"

        with patch.object(EducationEncoder, "load", return_value=mock_encoder):
            rag = EducationRAG(
                db_path,
                tmp_path / "model.onnx",  # not actually loaded
                tmp_path / "tokenizer.json",
            )
            # Override with our mock encoder
            rag._encoder = mock_encoder
            yield rag

    def test_search_returns_results(self, rag_with_data):
        results = rag_with_data.search("induction on natural numbers")
        assert len(results) > 0
        assert all(isinstance(r, EducationSearchResult) for r in results)

    def test_search_results_have_required_fields(self, rag_with_data):
        results = rag_with_data.search("induction", limit=1)
        r = results[0]
        assert r.text
        assert r.location
        assert r.browser_path
        assert isinstance(r.score, float)
        assert isinstance(r.code_blocks, list)

    def test_search_respects_limit(self, rag_with_data):
        results = rag_with_data.search("anything", limit=2)
        assert len(results) <= 2

    def test_search_location_format(self, rag_with_data):
        results = rag_with_data.search("induction", limit=1)
        # Location should be "VOLUME > chapter > section"
        loc = results[0].location
        assert ">" in loc
        assert "LF" in loc.upper()

    def test_search_browser_path_format(self, rag_with_data):
        results = rag_with_data.search("induction", limit=1)
        path = results[0].browser_path
        assert "software-foundations" in path
        assert "lf/" in path
        assert ".html" in path

    def test_search_volume_filter(self, rag_with_data):
        results = rag_with_data.search("anything", volume_filter="lf")
        for r in results:
            assert r.metadata.volume == "lf"

    def test_is_available_true_when_loaded(self, rag_with_data):
        assert rag_with_data.is_available()


class TestEducationRAGUnavailable:
    """EducationRAG handles missing resources gracefully."""

    def test_is_available_false_when_db_missing(self, tmp_path):
        rag = EducationRAG.__new__(EducationRAG)
        rag._encoder = None
        rag._index = None
        rag._chunks = {}
        assert not rag.is_available()


# ═══════════════════════════════════════════════════════════════════════════
# 5. MCP Tool Handler
# ═══════════════════════════════════════════════════════════════════════════


class TestHandleEducationContext:
    """handle_education_context MCP tool handler."""

    def test_returns_error_when_rag_unavailable(self):
        from Poule.education.handler import handle_education_context

        ctx = Mock()
        ctx.education_rag = None
        result = handle_education_context(ctx, query="induction")
        assert result["isError"] is True
        text = result["content"][0]["text"]
        assert "EDUCATION_UNAVAILABLE" in text

    def test_returns_results_when_rag_available(self):
        from Poule.education.handler import handle_education_context

        mock_result = EducationSearchResult(
            text="Induction is a key technique",
            code_blocks=["Theorem plus_comm : ..."],
            metadata=ChunkMetadata(
                volume="lf",
                volume_title="Logical Foundations",
                chapter="Basics",
                chapter_file="Basics.html",
                section_title="Induction",
                section_path=["Induction"],
                anchor_id="lab15",
            ),
            score=0.85,
            location="LF > Basics > Induction",
            browser_path="~/poule-home/software-foundations/lf/Basics.html#lab15",
        )
        ctx = Mock()
        ctx.education_rag = Mock(spec=EducationRAG)
        ctx.education_rag.is_available.return_value = True
        ctx.education_rag.search.return_value = [mock_result]

        result = handle_education_context(ctx, query="induction", limit=3)
        assert result["isError"] is False
        text = result["content"][0]["text"]
        parsed = json.loads(text)
        assert len(parsed["results"]) == 1
        assert parsed["results"][0]["location"] == "LF > Basics > Induction"

    def test_clamps_limit(self):
        from Poule.education.handler import handle_education_context

        ctx = Mock()
        ctx.education_rag = Mock(spec=EducationRAG)
        ctx.education_rag.is_available.return_value = True
        ctx.education_rag.search.return_value = []

        handle_education_context(ctx, query="test", limit=50)
        call_args = ctx.education_rag.search.call_args
        assert call_args[1].get("limit", call_args[0][1] if len(call_args[0]) > 1 else 10) <= 10

    def test_passes_volume_filter(self):
        from Poule.education.handler import handle_education_context

        ctx = Mock()
        ctx.education_rag = Mock(spec=EducationRAG)
        ctx.education_rag.is_available.return_value = True
        ctx.education_rag.search.return_value = []

        handle_education_context(ctx, query="test", volume="lf")
        call_args = ctx.education_rag.search.call_args
        assert call_args[1].get("volume_filter") == "lf" or "lf" in str(call_args)
